import { useMemo, useState } from 'react';
import { BarChart3, Bell, Check, ChevronRight, FileText, FolderKanban, Globe2, LayoutDashboard, LogOut, Menu, MessageSquare, MoreHorizontal, Plus, Save, Search, Settings, Sparkles, Trash2, Users, X } from 'lucide-react';

type View = 'overview' | 'content' | 'work' | 'inquiries' | 'analytics' | 'settings';
type Inquiry = { id: number; name: string; email: string; type: string; status: 'NEW' | 'REVIEWING' | 'CONTACTED'; time: string };

const initialInquiries: Inquiry[] = [
  { id: 1, name: 'Ava Studio', email: 'hello@example.com', type: 'DIGITAL PLATFORM', status: 'NEW', time: '12 min ago' },
  { id: 2, name: 'Northline', email: 'team@example.com', type: 'BRAND IDENTITY', status: 'REVIEWING', time: '2 hr ago' },
  { id: 3, name: 'Lumen Objects', email: 'studio@example.com', type: 'E-COMMERCE', status: 'CONTACTED', time: 'Yesterday' }
];

const nav: { id: View; label: string; icon: typeof LayoutDashboard }[] = [
  { id: 'overview', label: 'Overview', icon: LayoutDashboard },
  { id: 'content', label: 'Site content', icon: FileText },
  { id: 'work', label: 'Projects', icon: FolderKanban },
  { id: 'inquiries', label: 'Inquiries', icon: MessageSquare },
  { id: 'analytics', label: 'Analytics', icon: BarChart3 },
  { id: 'settings', label: 'Settings', icon: Settings }
];

const persist = (key: string, value: unknown) => localStorage.setItem(`aer-admin:${key}`, JSON.stringify(value));
const read = <T,>(key: string, fallback: T): T => { try { const raw = localStorage.getItem(`aer-admin:${key}`); return raw ? JSON.parse(raw) as T : fallback; } catch { return fallback; } };

function Stat({ label, value, detail }: { label: string; value: string; detail: string }) {
  return <div className="rounded-2xl border border-white/8 bg-white/[0.025] p-5"><p className="text-[9px] uppercase tracking-[0.2em] text-white/35">{label}</p><p className="mt-3 font-editorial text-4xl text-white">{value}</p><p className="mt-2 text-[10px] tracking-[0.05em] text-[#40E0D0]">{detail}</p></div>;
}

function Overview({ inquiries, setView }: { inquiries: Inquiry[]; setView: (v: View) => void }) {
  const newCount = inquiries.filter(i => i.status === 'NEW').length;
  return <div className="space-y-6">
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Site status" value="LIVE" detail="Production ready"/><Stat label="New inquiries" value={String(newCount).padStart(2, '0')} detail="Needs attention"/><Stat label="Projects" value="07" detail="Portfolio items"/><Stat label="Conversion" value="4.8%" detail="+0.9% this month"/></div>
    <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]">
      <section className="rounded-2xl border border-white/8 bg-white/[0.025] p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] tracking-[0.2em] text-[#40E0D0]">ACTIVITY</p><h2 className="mt-2 font-editorial text-3xl">Site pulse</h2></div><span className="rounded-full border border-[#40E0D0]/20 px-3 py-1 text-[8px] tracking-[0.15em] text-[#40E0D0]">LIVE</span></div><div className="mt-8 flex h-40 items-end gap-2">{[28,42,35,64,48,76,58,82,70,91,68,88,76,96].map((n,i)=><div key={i} className="flex-1 rounded-t bg-[#40E0D0]/50 transition-all hover:bg-[#40E0D0]" style={{height:`${n}%`}} />)}</div><div className="mt-4 flex justify-between text-[8px] uppercase tracking-[0.15em] text-white/25"><span>14 days ago</span><span>Today</span></div></section>
      <section className="rounded-2xl border border-white/8 bg-white/[0.025] p-6"><p className="text-[9px] tracking-[0.2em] text-[#40E0D0]">QUICK ACTIONS</p><div className="mt-5 space-y-2">{[['Edit hero','content'],['Add project','work'],['Review inquiries','inquiries'],['Open live site','overview']].map(([label,target])=><button key={label} onClick={()=>target==='overview'?window.open('/', '_blank'):setView(target as View)} className="flex w-full items-center justify-between rounded-xl border border-white/8 px-4 py-4 text-left text-[10px] uppercase tracking-[0.12em] text-white/65 transition hover:border-[#40E0D0]/30 hover:text-white"><span>{label}</span><ChevronRight size={14}/></button>)}</div></section>
    </div>
    <section className="rounded-2xl border border-white/8 bg-white/[0.025] p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] tracking-[0.2em] text-[#40E0D0]">INBOX</p><h2 className="mt-2 font-editorial text-3xl">Latest inquiries</h2></div><button onClick={()=>setView('inquiries')} className="text-[9px] uppercase tracking-[0.15em] text-white/35 hover:text-white">View all</button></div><div className="mt-6 divide-y divide-white/8">{inquiries.slice(0,3).map(i=><div key={i.id} className="flex items-center justify-between py-4"><div><p className="text-[11px] text-white/80">{i.name}</p><p className="mt-1 text-[9px] tracking-[0.08em] text-white/30">{i.type} · {i.time}</p></div><span className={`rounded-full px-3 py-1 text-[8px] tracking-[0.12em] ${i.status==='NEW'?'bg-[#40E0D0]/10 text-[#40E0D0]':'bg-white/5 text-white/40'}`}>{i.status}</span></div>)}</div></section>
  </div>;
}

function Content() {
  const [hero, setHero] = useState(() => read('hero', { eyebrow: 'AER × VÆLOR', title: 'MAKE YOUR WEBSITE HIT THE SPOTLIGHT', subline: 'Digital experiences with editorial precision.' }));
  const [saved, setSaved] = useState(false);
  const save = () => { persist('hero', hero); setSaved(true); window.setTimeout(()=>setSaved(false),1800); };
  return <div className="max-w-4xl space-y-6"><div><p className="text-[9px] tracking-[0.2em] text-[#40E0D0]">EDITOR</p><h1 className="mt-2 font-editorial text-5xl">Site content</h1><p className="mt-2 text-[10px] tracking-[0.06em] text-white/30">Manage the content model used by the studio. Changes are saved locally until a production CMS is connected.</p></div><section className="rounded-2xl border border-white/8 bg-white/[0.025] p-6"><div className="flex items-center justify-between border-b border-white/8 pb-5"><div><p className="text-[9px] tracking-[0.18em] text-[#40E0D0]">01 · HERO</p><h2 className="mt-2 font-editorial text-3xl">Opening statement</h2></div><span className="text-[8px] uppercase tracking-[0.15em] text-white/25">Draft</span></div><div className="mt-6 space-y-5"><label className="block"><span className="text-[9px] uppercase tracking-[0.16em] text-white/35">Eyebrow</span><input value={hero.eyebrow} onChange={e=>setHero({...hero,eyebrow:e.target.value})} className="mt-2 w-full rounded-xl border border-white/8 bg-black/20 px-4 py-3 text-sm outline-none focus:border-[#40E0D0]/50"/></label><label className="block"><span className="text-[9px] uppercase tracking-[0.16em] text-white/35">Headline</span><textarea rows={3} value={hero.title} onChange={e=>setHero({...hero,title:e.target.value})} className="mt-2 w-full resize-none rounded-xl border border-white/8 bg-black/20 px-4 py-3 text-sm outline-none focus:border-[#40E0D0]/50"/></label><label className="block"><span className="text-[9px] uppercase tracking-[0.16em] text-white/35">Supporting line</span><input value={hero.subline} onChange={e=>setHero({...hero,subline:e.target.value})} className="mt-2 w-full rounded-xl border border-white/8 bg-black/20 px-4 py-3 text-sm outline-none focus:border-[#40E0D0]/50"/></label></div><div className="mt-6 flex justify-end"><button onClick={save} className="inline-flex items-center gap-2 rounded-full bg-[#40E0D0] px-5 py-3 text-[9px] font-semibold uppercase tracking-[0.15em] text-[#0A0A0A]">{saved?<Check size={13}/>:<Save size={13}/>} {saved?'Saved':'Save draft'}</button></div></section></div>;
}

function Projects() {
  const [projects, setProjects] = useState(() => read('projects', [
    { id:1,title:'AER / VÆLOR', category:'STUDIO', status:'PUBLISHED' },{id:2,title:'Lumen Objects',category:'E-COMMERCE',status:'DRAFT'},{id:3,title:'Northline',category:'BRAND',status:'PUBLISHED' }
  ]));
  const add = () => { const next={id:Date.now(),title:'Untitled project',category:'DIGITAL PLATFORM',status:'DRAFT'}; const value=[...projects,next]; setProjects(value); persist('projects',value); };
  const remove=(id:number)=>{const value=projects.filter((p:any)=>p.id!==id);setProjects(value);persist('projects',value)};
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[9px] tracking-[0.2em] text-[#40E0D0]">WORKSPACE</p><h1 className="mt-2 font-editorial text-5xl">Projects</h1></div><button onClick={add} className="inline-flex items-center justify-center gap-2 rounded-full border border-[#40E0D0]/40 px-5 py-3 text-[9px] uppercase tracking-[0.15em] text-[#40E0D0] hover:bg-[#40E0D0] hover:text-[#0A0A0A]"><Plus size={14}/> New project</button></div><div className="overflow-hidden rounded-2xl border border-white/8 bg-white/[0.025]"><div className="hidden grid-cols-[1fr_180px_120px_60px] border-b border-white/8 px-5 py-3 text-[8px] uppercase tracking-[0.15em] text-white/25 md:grid"><span>Project</span><span>Category</span><span>Status</span><span/></div>{projects.map((p:any)=><div key={p.id} className="grid gap-2 border-b border-white/8 px-5 py-5 last:border-0 md:grid-cols-[1fr_180px_120px_60px] md:items-center"><div><p className="text-[12px] text-white/80">{p.title}</p><p className="mt-1 text-[8px] text-white/25">ID {String(p.id).slice(-5)}</p></div><span className="text-[9px] tracking-[0.12em] text-white/40">{p.category}</span><span className={`w-fit rounded-full px-3 py-1 text-[8px] tracking-[0.1em] ${p.status==='PUBLISHED'?'bg-[#40E0D0]/10 text-[#40E0D0]':'bg-white/5 text-white/35'}`}>{p.status}</span><button onClick={()=>remove(p.id)} className="text-white/25 hover:text-red-300"><Trash2 size={14}/></button></div>)}</div></div>;
}

function Inquiries({ inquiries, setInquiries }: { inquiries: Inquiry[]; setInquiries: React.Dispatch<React.SetStateAction<Inquiry[]>> }) {
  const [query,setQuery]=useState('');
  const filtered=useMemo(()=>inquiries.filter(i=>(i.name+i.email+i.type).toLowerCase().includes(query.toLowerCase())),[inquiries,query]);
  const cycle=(id:number)=>setInquiries(current=>current.map(i=>i.id===id?{...i,status:i.status==='NEW'?'REVIEWING':i.status==='REVIEWING'?'CONTACTED':'CONTACTED'}:i));
  return <div className="space-y-6"><div><p className="text-[9px] tracking-[0.2em] text-[#40E0D0]">CRM</p><h1 className="mt-2 font-editorial text-5xl">Inquiries</h1></div><div className="flex items-center gap-3 rounded-xl border border-white/8 bg-white/[0.025] px-4 py-3"><Search size={15} className="text-white/25"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search inquiries..." className="w-full bg-transparent text-xs outline-none placeholder:text-white/20"/></div><div className="grid gap-3">{filtered.map(i=><article key={i.id} className="rounded-2xl border border-white/8 bg-white/[0.025] p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-3"><h2 className="font-editorial text-2xl">{i.name}</h2><span className="rounded-full bg-[#40E0D0]/10 px-3 py-1 text-[8px] tracking-[0.1em] text-[#40E0D0]">{i.type}</span></div><p className="mt-2 text-[10px] text-white/35">{i.email} · {i.time}</p></div><button onClick={()=>cycle(i.id)} className="rounded-full border border-white/10 px-4 py-2 text-[8px] uppercase tracking-[0.15em] text-white/45 hover:border-[#40E0D0]/30 hover:text-white">{i.status} · advance</button></div></article>)}{!filtered.length&&<div className="py-16 text-center text-[10px] text-white/25">No inquiries found.</div>}</div></div>;
}

function Analytics() { return <div className="space-y-6"><div><p className="text-[9px] tracking-[0.2em] text-[#40E0D0]">OBSERVATORY</p><h1 className="mt-2 font-editorial text-5xl">Analytics</h1></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Visitors" value="12.4K" detail="+18.2%"/><Stat label="Sessions" value="18.9K" detail="+11.4%"/><Stat label="Avg. session" value="02:48" detail="+0:22"/><Stat label="Inquiry rate" value="4.8%" detail="+0.9%"/></div><section className="rounded-2xl border border-white/8 bg-white/[0.025] p-6"><p className="text-[9px] tracking-[0.18em] text-[#40E0D0]">TRAFFIC</p><div className="mt-8 flex h-64 items-end gap-2">{[32,45,38,55,42,68,52,74,61,79,72,88,65,92,76,96,83,89,78,98].map((n,i)=><div key={i} className="flex-1 rounded-t bg-white/10 hover:bg-[#40E0D0]/60" style={{height:`${n}%`}}/>)}</div></section></div> }

function SettingsView() { const [saved,setSaved]=useState(false); const save=()=>{setSaved(true);window.setTimeout(()=>setSaved(false),1600)}; return <div className="max-w-4xl space-y-6"><div><p className="text-[9px] tracking-[0.2em] text-[#40E0D0]">SYSTEM</p><h1 className="mt-2 font-editorial text-5xl">Settings</h1></div><section className="rounded-2xl border border-white/8 bg-white/[0.025] p-6 space-y-6"><div className="flex items-center justify-between border-b border-white/8 pb-5"><div><h2 className="font-editorial text-3xl">Studio configuration</h2><p className="mt-2 text-[10px] text-white/30">Operational preferences for the admin workspace.</p></div><Sparkles className="text-[#40E0D0]" size={18}/></div>{[['Studio name','AER × VÆLOR'],['Primary domain','vaelorstudio.vercel.app'],['Default status','Production'],['Timezone','Asia/Colombo']].map(([a,b])=><label key={a} className="block"><span className="text-[9px] uppercase tracking-[0.16em] text-white/35">{a}</span><input defaultValue={b} className="mt-2 w-full rounded-xl border border-white/8 bg-black/20 px-4 py-3 text-sm outline-none focus:border-[#40E0D0]/50"/></label>)}<div className="flex justify-end"><button onClick={save} className="inline-flex items-center gap-2 rounded-full bg-[#40E0D0] px-5 py-3 text-[9px] font-semibold uppercase tracking-[0.15em] text-[#0A0A0A]">{saved?<Check size={13}/>:<Save size={13}/>} {saved?'Saved':'Save settings'}</button></div></section><section className="rounded-2xl border border-amber-300/10 bg-amber-300/[0.02] p-5"><p className="text-[9px] uppercase tracking-[0.16em] text-amber-200/60">Production note</p><p className="mt-2 max-w-2xl text-[10px] leading-5 text-white/30">This panel is currently a frontend control surface with local persistence. Authentication, database writes, media storage, audit logs, and role permissions should be connected server-side before exposing /admin publicly.</p></section></div> }

export default function Admin() {
  const [view,setView]=useState<View>('overview'); const [mobile,setMobile]=useState(false); const [inquiries,setInquiries]=useState<Inquiry[]>(()=>read('inquiries',initialInquiries));
  const navigate=(next:View)=>{setView(next);setMobile(false)};
  const content=view==='overview'?<Overview inquiries={inquiries} setView={navigate}/>:view==='content'?<Content/>:view==='work'?<Projects/>:view==='inquiries'?<Inquiries inquiries={inquiries} setInquiries={v=>{setInquiries(v);persist('inquiries',v)}}/>:view==='analytics'?<Analytics/>:<SettingsView/>;
  return <div className="min-h-screen bg-[#0B0B0B] text-[#FAF8F5]" style={{fontFamily:'Inter, sans-serif'}}><div className="flex min-h-screen"><aside className={`fixed inset-y-0 left-0 z-50 w-64 border-r border-white/8 bg-[#0B0B0B] p-5 transition-transform md:static md:translate-x-0 ${mobile?'translate-x-0':'-translate-x-full'}`}><div className="flex items-center justify-between"><div><p className="text-sm font-medium tracking-[0.2em]">AER × VÆLOR</p><p className="mt-1 text-[8px] tracking-[0.2em] text-white/25">CONTROL / 01</p></div><button className="md:hidden" onClick={()=>setMobile(false)}><X size={18}/></button></div><nav className="mt-10 space-y-1">{nav.map(({id,label,icon:Icon})=><button key={id} onClick={()=>navigate(id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-[10px] uppercase tracking-[0.13em] transition ${view===id?'bg-[#40E0D0]/10 text-[#40E0D0]':'text-white/35 hover:bg-white/5 hover:text-white/75'}`}><Icon size={15}/>{label}{id==='inquiries'&&<span className="ml-auto rounded-full bg-[#40E0D0] px-2 py-0.5 text-[7px] font-semibold text-[#0B0B0B]">{inquiries.filter(i=>i.status==='NEW').length}</span>}</button>)}</nav><div className="absolute bottom-5 left-5 right-5 border-t border-white/8 pt-4"><a href="/" className="flex items-center gap-3 px-3 py-2 text-[9px] uppercase tracking-[0.13em] text-white/30 hover:text-white"><Globe2 size={14}/> View website</a><button onClick={()=>window.location.reload()} className="mt-1 flex w-full items-center gap-3 px-3 py-2 text-[9px] uppercase tracking-[0.13em] text-white/30 hover:text-white"><LogOut size={14}/> Exit panel</button></div></aside><div className="flex min-w-0 flex-1 flex-col"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-white/8 bg-[#0B0B0B]/90 px-5 backdrop-blur-xl md:px-8"><button className="md:hidden" onClick={()=>setMobile(true)}><Menu size={19}/></button><div className="hidden items-center gap-2 text-[9px] uppercase tracking-[0.15em] text-white/25 md:flex"><span>ADMIN</span><ChevronRight size={12}/><span className="text-white/55">{nav.find(n=>n.id===view)?.label}</span></div><div className="ml-auto flex items-center gap-4"><span className="hidden text-[8px] uppercase tracking-[0.15em] text-[#40E0D0] sm:block">Production</span><button className="text-white/30 hover:text-white"><Bell size={16}/></button><div className="flex h-8 w-8 items-center justify-center rounded-full border border-white/10 bg-white/5 text-[9px]">A</div></div></header><main className="w-full p-5 md:p-8 xl:p-10">{content}</main></div></div>{mobile&&<button aria-label="Close menu" onClick={()=>setMobile(false)} className="fixed inset-0 z-40 bg-black/60 md:hidden"/>}</div>;
}
