import { motion } from 'framer-motion';

const projects = [
  { id: '01', title: 'Digital Identity', category: 'Brand × Web', description: 'A digital identity system built to make a brand feel distinct, credible, and unmistakably its own.', tags: ['Art direction', 'UI/UX', 'Motion'], visual: 'identity' },
  { id: '02', title: 'Editorial Commerce', category: 'E-commerce × Experience', description: 'A considered commerce experience where product, typography, and interaction work as one editorial system.', tags: ['UX strategy', 'Web design', 'Development'], visual: 'commerce' },
  { id: '03', title: 'Spatial Interface', category: 'Digital Product × Motion', description: 'A responsive interface using depth and motion with restraint, giving complex information a clearer visual hierarchy.', tags: ['Product design', 'Interaction', 'Creative development'], visual: 'spatial' }
];

function ProjectVisual({ type }: { type: string }) {
  if (type === 'identity') return <div className="relative h-full w-full overflow-hidden bg-aer-cream text-aer-black p-6 md:p-10 flex flex-col justify-between"><div className="flex justify-between text-[8px] tracking-[0.25em] uppercase"><span>AER / 001</span><span>Identity system</span></div><div className="font-editorial text-[18vw] md:text-[10vw] leading-[0.7] tracking-[-0.05em]">A/</div><div className="flex justify-between items-end text-[8px] tracking-[0.2em] uppercase"><span>Form follows feeling</span><span>2026</span></div></div>;
  if (type === 'commerce') return <div className="relative h-full w-full overflow-hidden bg-[#111] text-aer-cream p-6 md:p-10 flex flex-col"><div className="flex justify-between text-[8px] tracking-[0.25em] uppercase text-aer-cream/50"><span>AER / 002</span><span>Commerce study</span></div><div className="mt-auto"><div className="font-editorial italic text-[14vw] md:text-[8vw] leading-[0.7]">Objects</div><div className="mt-8 h-px w-full bg-aer-cream/20" /><div className="mt-3 flex justify-between text-[8px] tracking-[0.2em] uppercase text-aer-cream/50"><span>Selection / Context / Intent</span><span className="text-aer-blue">Explore ↗</span></div></div></div>;
  return <div className="relative h-full w-full overflow-hidden bg-aer-black flex items-center justify-center"><div className="absolute inset-8 border border-aer-cream/10" /><motion.div animate={{ rotate: 360 }} transition={{ duration: 18, repeat: Infinity, ease: 'linear' }} className="relative h-40 w-40 md:h-56 md:w-56 rounded-full border border-aer-blue/40"><div className="absolute left-1/2 top-0 h-full w-px -translate-x-1/2 bg-aer-blue/20" /><div className="absolute left-0 top-1/2 h-px w-full -translate-y-1/2 bg-aer-blue/20" /><div className="absolute inset-1/4 rounded-full border border-aer-cream/20" /></motion.div><span className="absolute text-[8px] tracking-[0.3em] uppercase text-aer-cream/60">Spatial / 003</span></div>;
}

export default function Work() {
  return <section id="work" className="relative bg-aer-charcoal px-6 py-28 md:px-12 md:py-40"><div className="mx-auto max-w-7xl"><div className="mb-16 flex items-end justify-between gap-8 md:mb-24"><div><p className="mb-5 text-[9px] tracking-[0.35em] text-aer-blue uppercase">Selected work</p><h2 className="font-editorial text-6xl leading-[0.85] tracking-[-0.03em] md:text-8xl lg:text-[9rem]">Built with<br /><span className="italic text-aer-cream/60">intent.</span></h2></div><p className="hidden max-w-xs text-xs leading-relaxed text-aer-cream/50 md:block">A small selection of digital experiences. Every project starts with a problem, then earns its visual language.</p></div><div className="space-y-24 md:space-y-32">{projects.map((project) => <motion.article key={project.id} initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-10% 0px' }} transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }} className="group"><div className="grid gap-8 md:grid-cols-[1fr_0.38fr] md:gap-12"><div className="aspect-[16/10] overflow-hidden"><ProjectVisual type={project.visual} /></div><div className="flex flex-col justify-between py-1"><div><div className="mb-7 flex items-center justify-between border-b border-aer-cream/10 pb-4 text-[8px] tracking-[0.25em] uppercase text-aer-cream/40"><span>Project {project.id}</span><span>{project.category}</span></div><h3 className="font-editorial text-4xl leading-none md:text-5xl">{project.title}</h3><p className="mt-5 max-w-sm text-sm leading-relaxed text-aer-cream/55">{project.description}</p></div><div className="mt-10 flex flex-wrap gap-2">{project.tags.map((tag) => <span key={tag} className="border border-aer-cream/10 px-3 py-2 text-[8px] tracking-[0.15em] uppercase text-aer-cream/45">{tag}</span>)}</div></div></div></motion.article>)}</div><div className="mt-24 border-t border-aer-cream/10 pt-6 flex items-center justify-between"><span className="text-[8px] tracking-[0.3em] uppercase text-aer-cream/30">More work on request</span><a href="#contact" className="text-[9px] tracking-[0.2em] uppercase text-aer-blue hover:text-aer-cream transition-colors">Start a project ↗</a></div></div></section>;
}
